package com.bofu.tictactoetdd

enum class RedLine {
    HORIZONTAL_UP,
    HORIZONTAL_MIDDLE,
    HORIZONTAL_DOWN,
    VERTICAL_LEFT,
    VERTICAL_MIDDLE,
    VERTICAL_RIGHT,
    DIAGONAL_LEFT,
    DIAGONAL_RIGHT,
}